name: Build

permissions:
  deployments: write

on:
  push:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
        description: The tag to use

env:
  NODE_VERSION: 18.15.0
  NPM_VERSION: 9.5.0
  PYTHON_VERSION: 3.8

jobs:
  build-vsix:
    name: Build VSIX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: microsoft/vscode-jupyter
          ref: ${{ github.event.inputs.ref }}

      - name: Install dependencies for native modules
        run: |
          sudo apt-get update
          sudo apt-get install libpango1.0-dev libgif-dev

      - name: Use Node ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Use Npm ${{env.NPM_VERSION}}
        run: npm i -g npm@${{env.NPM_VERSION}}

      - name: Use Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - run: npm i -g @vscode/vsce

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_build_from_source: true
        shell: bash
        run: |
          VSC_VSCE_TARGET=linux-arm64 npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=linux-arm64 npm run prePublishBundle && vsce package --target=linux-arm64
          VSC_VSCE_TARGET=linux-armhf npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=linux-armhf npm run prePublishBundle && vsce package --target=linux-armhf
          VSC_VSCE_TARGET=alpine-x64 npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=alpine-x64 npm run prePublishBundle && vsce package --target=alpine-x64
          VSC_VSCE_TARGET=alpine-arm64 npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=alpine-arm64 npm run prePublishBundle && vsce package --target=alpine-arm64
          VSC_VSCE_TARGET=linux-x64 npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=linux-x64 npm run prePublishBundle && vsce package --target=linux-x64
          VSC_VSCE_TARGET=darwin-arm64 npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=darwin-arm64 npm run prePublishBundle && vsce package --target=darwin-arm64
          VSC_VSCE_TARGET=darwin-x64 npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=darwin-x64 npm run prePublishBundle && vsce package --target=darwin-x64
          VSC_VSCE_TARGET=win32-x64 npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=win32-x64 npm run prePublishBundle && vsce package --target=win32-x64
          VSC_VSCE_TARGET=win32-arm64 npm ci --foreground-scripts --prefer-offline && VSC_VSCE_TARGET=win32-arm64 npm run prePublishBundle && vsce package --target=win32-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.vsix"
