name: Build

permissions:
  deployments: write

on:
  push:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
        description: The tag to use

env:
  NODE_VERSION: 18.15.0
  NPM_VERSION: 9.5.0
  PYTHON_VERSION: 3.8

jobs:
  build-vsix:
    name: Build VSIX for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, alpine-x64, alpine-arm64, linux-x64, darwin-arm64, darwin-x64, win32-x64, win32-arm64]
    env:
      VSC_VSCE_TARGET: ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: microsoft/vscode-jupyter
          ref: ${{ github.event.inputs.ref }}

      - name: Install dependencies for native modules
        if: contains(matrix.target, 'linux') || contains(matrix.target, 'alpine')
        run: |
          sudo apt-get update
          sudo apt-get install libpango1.0-dev libgif-dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup NPM
        run: npm i -g npm@${{ env.NPM_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install VSCE
        run: npm i -g @vscode/vsce

      - name: Build and Package
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_build_from_source: true
        run: |
          npm ci --foreground-scripts --prefer-offline
          npm run prePublishBundle
          vsce package --target=${{ env.VSC_VSCE_TARGET }}

      - uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.target }}
          path: "*.vsix"
